[package]
name = "fs"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
parking_lot = { version = "0.12", features = ["nightly"] }
wasi = "0.11.0+wasi-snapshot-preview1"
